apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadkydm5299-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadkydm5299-tenant-component
    app.kubernetes.io/part-of: loadkydm5299-tenant-app
  name: loadkydm5299-tenant-component
  namespace: loadkydm5299-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadkydm5299-tenant-component
    weight: null
status: {}
