apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadkydm5299-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadkydm5299-tenant-component
    app.kubernetes.io/part-of: loadkydm5299-tenant-app
  name: loadkydm5299-tenant-component
  namespace: loadkydm5299-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: loadkydm5299-tenant-component
status:
  loadBalancer: {}
